### ISSUE TITLE
Press Tab twice to insert tab

### ISSUE THREAD

**Issue by alefi87** [oleksiyk/SublimeTabSnippets#1]
Currently if you're not using snippets you have to hit Tab twice in order to actually insert a tab. 
Can this be fixed to work properly with and without snippets?

**Comment by oleksiyk** [comment]
I'm not sure I understand the problem. 

Check other Sublime Text completion settings, for example I have the following:

```
"auto_complete_commit_on_tab": false,
"tab_completion": false,
```

**Comment by alefi87** [comment]
Sorry, let me elaborate.
If I don't use _any_ custom key bindings, use the above custom settings, use this plugin, but have _no custom snippets_ then I have to hit Tab twice to actually insert the \t character. 

My guess is that when auto-complete selection is visible, the first Tab keypress triggers your command which in turn triggers insert_best_completion. But if there is no best completion? Nothing happens. So I actually have to hit Tab again to insert \t.

Does that make more sense?

**Comment by oleksiyk** [comment]
Try a5c9455

**Comment by alefi87** [comment]
That fixed it. Thanks a lot! Finally someone who fixed this annoying "feature" in ST.
